### ISSUE TITLE
Chapter 3 - npm run sass issue on Windows 10

### ISSUE THREAD

**Issue by Akamitori** [chrissainty/blazor-in-action#19]
Greetings. I am going through the book.

Apparently the following 
`
    <Exec Command="npm run sass -- %(ScopedScssFiles.Identiy) %(relativedir)%(filename).css" />
    `

  Runs into issues and and as a result the build fails.
  
  This is the error code 
  
![image](https://user-images.githubusercontent.com/78937210/151268696-76784cdb-24be-4f52-aba9-085f3fbc7449.png)

and this the output from the build 
![image](https://user-images.githubusercontent.com/78937210/151270037-559d896a-502e-4a3a-ae43-a31e8f95744c.png)

OS : Windows 10
IDE : Visual Studio 2022

I checked out chapter 4 and the same issue occurred as well.

**Comment by chrissainty** [comment]
I've doubled check this and it is all working as expected. Looking at your screenshots, you appear to have double forward slashes in the path to the scss file and output css file. I would check you code against at in this repo and see if you've missed something.

**Comment by qwinmen** [comment]
I am get this error too (Получил похожую ошибку):
![image](https://github.com/chrissainty/blazor-in-action/assets/22964689/93561f41-c705-4011-8ad9-9f719323b2c8)
Build Output:
![image](https://github.com/chrissainty/blazor-in-action/assets/22964689/040fdb6c-99f5-4782-9613-35760f205a7a)

Fix (Решение):
- You should probably upgrade to a newer version of node (Поставить более свежую версию node):
![image](https://github.com/chrissainty/blazor-in-action/assets/22964689/4a92c73d-d233-4159-a598-783f9d47f079)
