### ISSUE TITLE
NO no-image.jpg in repository that I can find

### ISSUE THREAD

**Issue by MrMoot** [chrissainty/blazor-in-action#20]
In chapter 6 (pg. 175) when adding the image upload functionality, you mention that we can use the "no-image.jpg" in the accompanying GitHub repo, but I couldn't find one.  Not a big deal, just thought I would mention it.  (EDIT: retrieving a "NO-IMAGE" image from placeholder, covered in chapter 7, would explain why it is not in the repo - perhaps removing the text related to "no-image.jpg" on pg. 175 and mentioning we will cover the case of no image in the next chapter would be better than putting it into the repo).

This is not an "Issue" but when copying the code from the PDF I downloaded, I get #<Letter> and [CA] copied that need to be removed in order for the code to be clean.  It might be nice if the #<Letter> had commenting characters before them so it could be copied without having to remove them.  I'm not sure about the "[CA]" (some artifact of converting you figures to PDF format?), but the #<Letter> and the "[CA]" create opportunity for me to screw things up.

**Comment by ghhv** [comment]
Yes, that "[CA]" corruption is a mega pain in the butt..
![image](https://user-images.githubusercontent.com/13160762/159155584-b79a0c4c-b938-4d3e-9ba4-2ecb23774fc7.png)
I've been copying from this repository instead but that is sometimes not in line with the book.

**Comment by chrissainty** [comment]
@MrMoot The no-image.jpg is legacy for an older iteration of the chapter and has since been dropped. The text on the MEAP should have been updated.

@ghhv The [CA] is a formatting marker I have to add in for Manning to use to position line breaks when the code is printed. They are aware of the issues it creates for the MEAP version and I hope it will be rectrifed ASAP.

**Comment by ghhv** [comment]
@chrissainty yes, I didn't think it was your fault.. I also logged a support call to Manning about it.. It's made doing the last 4 chapters so, so annoying and slow. 

And those A, B, C, D, E code highlights also stop selection for copy paste.. makes it near useless. 

And that text has still not been updated re: the no-image as at a few days ago when I did that chapter.

**Comment by ghhv** [comment]
@chrissainty - looks like they removed the "[CA]"s but not the extra newlines which were added so it's still a mess.. Thanks.
![image](https://user-images.githubusercontent.com/13160762/160108446-e905287b-be2e-401e-ae9e-360fe5fd56a9.png)
