### ISSUE TITLE
Chapter 3 Drawer does not open in Chrome with Debug -> Start without debugging

### ISSUE THREAD

**Issue by hazelbrook** [chrissainty/blazor-in-action#21]
I am working through and enjoying Blazor in Action.
I came across this issue today.

Steps to reproduce:

1. Open the Chapter 3 solution in VS 2022
2. Set Chrome as the Browser
3. Debug -> Start without Debugging
4. Click View on any trail
5. Observe the drawer does not pop/slide out but appears at the top of the page

Debug -> Start Debugging.. works ok
Edge and Firefox works ok

Possibly arising from a recent Chrome update

![image](https://user-images.githubusercontent.com/29762480/163211702-f9a1d078-ef1c-4879-8eb1-5e1dfc9edfe7.png)

**Comment by chrissainty** [comment]
Have you tried clearing the browser cache? This issue comes up time and time again and it's almost always a caching issue.

**Comment by hazelbrook** [comment]
Yes this resolves the issue. Thanks.

**Comment by hazelbrook** [comment]
Clearing the browser cache resolved the issue.
