### ISSUE TITLE
Validation Bug - Route Instruction Description Property Not Being Used

### ISSUE THREAD

**Issue by DeckardKain** [chrissainty/blazor-in-action#28]
Hi Chris,

Thank you for this amazing book! I am following along and I have encountered a puzzling situation and for my own learning and understanding I wanted to reach out to see if I could find out what is happening here.

Chapter 5 Section 2 Subsection 2 (5.2.2)

It appears that the validation for the Route Instructions section Description input text box is getting mixed up with the TrailDto's Description property instead. I confirmed this by modifying the validation message for the RouteInstruction's Description and still received the validation message for the TrailDto's Description property.

In addition, I changed the name of the RouteInstruction's Description property to Describ and the validation no longer gets the two confused but also does not provide any validation.

Are you able to provide some clarity here?

I attempted this with the versions of frameworks consistent with the builds in chapter 5.

I also attempted this with updated versions of Fluent, and received the same behaviour.

Client Project - Blazored.FluentValidation 2.1.0
API Project - FluentValidation.AspNetCore 11.2.2

**Comment by chrissainty** [comment]
Hi @DeckardKain,

I'm glad you're enjoying the book. My apologies for the error you're experiencing. There is a missing line in the `TrailDto` validator config that is causing the validation issues. Updating the `TrailValidator` to the following will fix the issue.

```csharp
public class TrailValidator : AbstractValidator<TrailDto>
{
    public TrailValidator()
    {
        RuleFor(x => x.Name).NotEmpty().WithMessage("Please enter a name");
        RuleFor(x => x.Description).NotEmpty().WithMessage("Please enter a description");
        RuleFor(x => x.Location).NotEmpty().WithMessage("Please enter a location");
        RuleFor(x => x.Length).GreaterThan(0).WithMessage("Please enter a length");
        RuleForEach(x => x.Route).SetValidator(new RouteInstructionValidator()); // <-- Missing line
    }
}
```
