### ISSUE TITLE
ENUM Problem

### ISSUE THREAD

**Issue by DeckardKain** [chrissainty/blazor-in-action#29]
Hi Chris,

As per the screenshot below, the TrailDto does not like having a property the same name as the enum. I have attempted to resolve this by renaming the enum or the property but nothing I do resolves the error in the EditTrailPage.razor in the SubmitEditTrail method, see screenshot #2. Do you know what I can do to resolve this? Thank you!

![image](https://user-images.githubusercontent.com/58267324/223204402-8a28e57a-ce58-4ee4-82be-0bf26453505e.png)

![image](https://user-images.githubusercontent.com/58267324/223204748-0143ab7c-55bc-4e9a-9868-da401ff4c879.png)

**Comment by chrissainty** [comment]
Hi @DeckardKain. The issue is that you've put the enum inside the `TrailDto` class. It should be outside it. That's why you're seeing a naming conflict.

**Comment by DeckardKain** [comment]
Thanks Chris for the clarification! I just wanted to double check to make sure I wasn't missing anything for my own learning. Do not nest your enum in a class and name it the same as a property in said class. Seems very obvious now haha oops!
