### ISSUE TITLE
I can't debug, it seems like it's in Release mode

### ISSUE THREAD

**Issue by DominusDRR** [chrissainty/blazor-in-action#33]
Hi. 

I bought your book to learn a bit of Blazor, I followed the examples up to chapter 4

I wanted to understand something, so I put some breakpoints in a blazor file, but they remain disabled

I attached an image for clarity.

![image](https://github.com/user-attachments/assets/56eb81b4-848e-4a13-b167-7e69ca9304c1)

I have tried all possible suggestions on the internet, including uninstalling and updating visual studio, but I can't get it to work.

Any comments or suggestions are welcome.

Regards

**Comment by chrissainty** [comment]
I'm not sure what the issue is. I don't use Visual Studio, I use Rider so I'm not familiar with its current qwerks. 

I'd suggest raising something on the ASP.NET core repo.

**Comment by DominusDRR** [comment]
Hi.

Thank you very much for replying.

I suspect it is some configuration, or the versions of the packages with which I managed to recreate your examples.

I will continue with your book, and then I will try to create the project from scratch (Chapter 2 or 3) and determine where the problem starts from.

If you have any additional comments, I would like to read them, otherwise I will close the case.

Thanks again for writing.

Regards

**Comment by DominusDRR** [comment]
The problem seems to be a Visual Studio configuration. Only blazor files, can't be debugged. (@code)
